{% set name = "s3path" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33cf732e2b73582e11e09f957bc475cc60237abd40f928973cf5ce0a4cf67b3d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - boto3 >=1.16.35
    - smart_open
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - s3path

about:
  home: https://github.com/liormizr/s3path
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pathlib Extension for AWS S3 Service, to provide File-System/Path like interface

extra:
  recipe-maintainers:
    - liormizr
