{% set name = "s3path" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0116416f30bf016c08c396c1a77659281d39bb05f742987782b74f71594c79c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - boto3 >=1.16.35
    - smart_open
    - packaging

test:
  requires:
    - python {{ python_min }}
  imports:
    - s3path

about:
  home: https://github.com/liormizr/s3path
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pathlib Extension for AWS S3 Service, to provide File-System/Path like interface

extra:
  recipe-maintainers:
    - liormizr
